### ISSUE TITLE
Failing Checks when Netlify Builds are cancelled.

### ISSUE THREAD

**Issue by AllusInteractive** [Reece-Morgan/nx-monorepo#33]
Raising this here, although it is an issue with **Netlify**, and not with my codebase. This is here more as a notice/reminder of why certain builds might be failing.

There is a known issue with Netlify that a cancelled build is reported as a failure. So even though these builds have 'failed', they were actually cancelled in Netlify 

![image](https://user-images.githubusercontent.com/56962521/183254952-3c798194-6411-4db9-87dc-ba10b9751687.png)

This is an issue that has been raised and requested in this issue [here](https://github.com/netlify/build/issues/1224). This was initally raised on the 3rd May 2020, and as of 24 days ago (from today, 6th August 2022) this issue has not yet been resolved. 

Again, these failed checks here are a result of an issue with Netlify, not because my builds are failing.

**Comment by Reece-Morgan** [comment]
deployment has been moved from netlify to vercel. This issue should no longer cause any problems
